(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/formId"],{"03bc":function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var r=c(n("b775")),o=c(n("0f88")),a=n("2f62");function c(e){return e&&e.__esModule?e:{default:e}}function u(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,r)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?u(n,!0).forEach((function(t){f(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):u(n).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function f(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}var l={name:"formId",data:function(){return{isLogin:o.default.returnIsLogin()||"",id:Date.now()*Math.random(),phone:wx.getStorageSync("phone")||""}},methods:i({},(0,a.mapMutations)(["setPhone"]),{submitOrder:function(e){"the formId is a mock one"!=e.mp.detail.formId&&r.default.POST({formId:e.detail.formId,type:1},"","/personal/addFormId")},getPhoneNumber:function(e){var t=this;o.default.returnIsLogin()?this.phone||e.target.encryptedData&&r.default.POST({phoneData:e.target.encryptedData,phoneIv:e.target.iv},"","/home/getWxPhone").then((function(e){t.phone=e,wx.setStorageSync("phone",e),t.setPhone(e)})).catch((function(e){console.log("获取手机号出错：",e)})):console.error("必须先登录才能获取电话号码")}})};t.default=l},"5a20e":function(e,t,n){"use strict";n.r(t);var r=n("03bc"),o=n.n(r);for(var a in r)"default"!==a&&function(e){n.d(t,e,(function(){return r[e]}))}(a);t["default"]=o.a},7683:function(e,t,n){"use strict";var r,o=function(){var e=this,t=e.$createElement;e._self._c},a=[];n.d(t,"b",(function(){return o})),n.d(t,"c",(function(){return a})),n.d(t,"a",(function(){return r}))},ca79:function(e,t,n){"use strict";n.r(t);var r=n("7683"),o=n("5a20e");for(var a in o)"default"!==a&&function(e){n.d(t,e,(function(){return o[e]}))}(a);var c,u=n("f0c5"),i=Object(u["a"])(o["default"],r["b"],r["c"],!1,null,"05c35a45",null,!1,r["a"],c);t["default"]=i.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/formId-create-component',
    {
        'components/formId-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("ca79"))
        })
    },
    [['components/formId-create-component']]
]);
